### ISSUE TITLE
Comment on Matryoshka Reflection

### ISSUE THREAD

**Issue by sahuang** [RaccoonNinja/Project-SEKAI-CTF-2022-Writeups#1]
Hi there,

First of all, thank you for playing SekaiCTF 2022 and glad you liked it!

I happened to see your comment for the challenge reflection on `Matryoshka`:

> Matryoshka: from PILlow to Apple iDOT pngs and smart health record and audio denoising
> the second part is cool but REALLY unfair, given there are no decoders or even sample scripts for players who don't have the correct version of iProducts. android solo players are getting punished for not being the cool kid

In fact, many teams solved it WITHOUT using any apple product. For example, this online forensics tool can be used to instantly view the different QRCode: https://fotoforensics.com/analysis.php?id=09c04e5dc76b5f0e97b0c846c13fae6bf802db81.311291

![Fotoforensics](https://cdn.discordapp.com/attachments/949155684031811589/1026710215598551160/unknown.png)

As written in our [writeup](https://github.com/project-sekai-ctf/sekaictf-2022/tree/main/misc/matryoshka/solution), you can also easily solve with online Apple browser testing tools, like [TestingBot](https://testingbot.com/).

I hope this clears things up or adds to your learning process. Thanks again!

**Comment by RaccoonNinja** [comment]
Thank you for shining a light on the site! I learned a lot from your CTF :smile_cat:
